Document: sni-proxy
Title: Debian sni-proxy Manual
Author: <insert document author here>
Abstract: This manual describes what sni-proxy is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/sni-proxy/sni-proxy.sgml.gz

Format: postscript
Files: /usr/share/doc/sni-proxy/sni-proxy.ps.gz

Format: text
Files: /usr/share/doc/sni-proxy/sni-proxy.text.gz

Format: HTML
Index: /usr/share/doc/sni-proxy/html/index.html
Files: /usr/share/doc/sni-proxy/html/*.html
